import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./markdown.css"
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative z-0 w-screen h-screen flex overflow-hidden">
          <div className="relative flex w-full h-full flex-col overflow-hidden">

            <Header />

            {/* We can not split the text input with display box because they effect to each other */}
            <div className="relative flex h-full max-w-full flex-1 flex-col overflow-hidden">
              {children}
            </div>

          </div>
        </div>
      </body>
    </html>
  );
}
